export enum ActionTypeEnum {
    SET_LOCALSTATE = 'SET_LOCALSTATE',
    REMOVE_LOCALSTATE = 'REMOVE_LOCALSTATE',
    SET_APP_STATE = 'SET_APP_STATE',
    UPDATE_STATE_FROM_LOCALSTORAGE = 'UPDATE_STATE_FROM_LOCALSTORAGE',
}